#Site settings subprojet name
baseurl: "/jekyll"
asseturl: "jekyll/assets"
#Dir name in _includes
skin: "iunui"
# langsite
lang:
 brandname: "Iu Núi"
 read_more: ">>"
 view: "XEM"
 showpostby: "danh mục: "
 postincat: "cùng mục"
 postintag: "cùng thẻ"
 ghim: "nổi bật"
#Build settings
markdown: kramdown
permalink: /:categories/:title
paginate: 6
paginate_path: /page:num
#
plugins:
 - jekyll-feed
 - jekyll-paginate
